version: "3.9"

services:
  app:
    image: amiril/quizhive_spring:latest
    container_name: quizhive_spring
    env_file: .env
    ports:
      - "${PORT}:8080"
    depends_on:
      - mongodb
    restart: unless-stopped

  # MongoDB service
  mongodb:
    container_name: quizhive_mongodb
    image: mongo:latest
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file: .env


volumes:
  quizhive_data:
    driver: local
