version: "3.9"

services:
  app:
    image: amiril/quizhive_spring:latest
#    build: .
    container_name: quizhive_spring
    env_file: .env
    ports:
      - "${PORT}:8080"
    depends_on:
      - mongodb
    restart: unless-stopped

  # MongoDB service
  mongodb:
    container_name: quizhive_mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    image: mongo:latest
    command:
      - --storageEngine
      - wiredTiger
#      - --auth
    ports:
      - "127.0.0.1:$MONGO_DB_PORT:27017"
    volumes:
      - quizhive_data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: unless-stopped

volumes:
  quizhive_data:
    driver: local
